# Generated by Django 5.2 on 2025-04-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_alter_stadium_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stadium',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stadiummanager',
            options={},
        ),
    ]
