# Generated by Django 5.2 on 2025-04-06 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_stadium', to='stadium.stadium'),
        ),
    ]
