# Generated by Django 5.2 on 2025-04-06 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='stadium_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stadiummanager',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_stadiums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stadiummanager',
            name='stadium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stadium_manager', to='stadium.stadium'),
        ),
    ]
